# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2b09516bc9e518a309fdf80525a818dbd276148d3b0834a4dd84b92235838542ae5b231613e76842a3dde00538c133976410cfa0592cf29d15d9146db19fa4b8

test:
  secret_key_base: cb4f929c564e64841febb464cd9787d80ccf27f73182662cf60fb9e512a3aedcccd0f46d389884ab1114b1abc9e2e8259fdccfc97754d3c2f16efd809956e2fb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
